schema = 3

[mod]
  [mod.'cel.dev/expr']
    version = 'v0.25.3'
    hash = 'sha256-W17jP8I+4zsPEUMahiOp94WxihvZVnbmGTofF+LL9C8='

  [mod.'github.com/Masterminds/semver/v3']
    version = 'v3.5.0'
    hash = 'sha256-Ps7gEw0nkHDZO/iDru/s+X8rMaUkNmiZ7id1GsIKlDU='

  [mod.'github.com/antlr4-go/antlr/v4']
    version = 'v4.13.1'
    hash = 'sha256-beAuxHNRUuhzcSJUh/8ztVf1zCUiaT72fg2Jvx0AuNQ='

  [mod.'github.com/beorn7/perks']
    version = 'v1.0.1'
    hash = 'sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4='

  [mod.'github.com/blang/semver/v4']
    version = 'v4.0.0'
    hash = 'sha256-dJC22MjnfT5WqJ7x7Tc3Bvpw9tFnBn9HqfWFiM57JVc='

  [mod.'github.com/cenkalti/backoff/v5']
    version = 'v5.0.3'
    hash = 'sha256-bKq43PPD8RM6e7HePxHaO27traqm76bkvHcTVTQ+jeY='

  [mod.'github.com/cespare/xxhash/v2']
    version = 'v2.3.0'
    hash = 'sha256-7hRlwSR+fos1kx4VZmJ/7snR7zHh8ZFKX+qqqqGcQpY='

  [mod.'github.com/davecgh/go-spew']
    version = 'v1.1.2-0.20180830191138-d8f796af33cc'
    hash = 'sha256-fV9oI51xjHdOmEx6+dlq7Ku2Ag+m/bmbzPo6A4Y74qc='

  [mod.'github.com/emicklei/go-restful/v3']
    version = 'v3.13.0'
    hash = 'sha256-lB2Z29RDLiVQE5NrsV1s2iHeQ4ciGwNj5OG1zJxwZV8='

  [mod.'github.com/evanphx/json-patch/v5']
    version = 'v5.9.11'
    hash = 'sha256-DaWzRi5dIr3U7kJlV3Qm1DWoKh5W+FI2BW/ATXT40J4='

  [mod.'github.com/felixge/httpsnoop']
    version = 'v1.1.0'
    hash = 'sha256-oePAjhI+dYRrMQAeUWnJ3o+PdHFU1tk1Z/R3/kGdjnw='

  [mod.'github.com/fsnotify/fsnotify']
    version = 'v1.10.1'
    hash = 'sha256-6LBLgsh4nKkMpgRKVsYFEaGDSU1fncBcWVSjKBdfgjU='

  [mod.'github.com/fxamacker/cbor/v2']
    version = 'v2.9.4'
    hash = 'sha256-9ApJh33oLwgBKYvINBjvwlWBAWXs8L3DN7yS9nyBXr0='

  [mod.'github.com/go-logr/logr']
    version = 'v1.4.4'
    hash = 'sha256-q9HX9aelONTLsywyLY4Wc5UYCK+wG0FbSzFWisCYiIA='

  [mod.'github.com/go-logr/stdr']
    version = 'v1.2.2'
    hash = 'sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE='

  [mod.'github.com/go-logr/zapr']
    version = 'v1.3.0'
    hash = 'sha256-ehak315/wxBKtuFhCz+TPsvNzYBv0/oZ3tVIjT52hc0='

  [mod.'github.com/go-openapi/jsonpointer']
    version = 'v1.0.1'
    hash = 'sha256-BY2CFp+7zfz8BrihxcFb2ngP/IFfEsyFjKIIDS/jj6g='

  [mod.'github.com/go-openapi/jsonreference']
    version = 'v1.0.2'
    hash = 'sha256-0Wh8CD1uT6WtRn6BOnfQzbdWt3p911ViOhVLvf81IlY='

  [mod.'github.com/go-openapi/swag']
    version = 'v0.29.2'
    hash = 'sha256-irSMBMl09cLihVKo7RvQYuKWaL3Y1CLEGXemLiRonrs='

  [mod.'github.com/go-openapi/swag/cmdutils']
    version = 'v0.29.2'
    hash = 'sha256-XEtACvkFdkFDUfVCmmdHXprPF2cceRD0u5L0XQg8Ts8='

  [mod.'github.com/go-openapi/swag/conv']
    version = 'v0.29.2'
    hash = 'sha256-MHG8zsICGJLxZhULNNnJWirtodAc7g2VRJ8WESwmC6I='

  [mod.'github.com/go-openapi/swag/fileutils']
    version = 'v0.29.2'
    hash = 'sha256-Up0HXdCjm0aWKE9wSEC8Bz1DwpxtKshIjXIJoh9ylPc='

  [mod.'github.com/go-openapi/swag/jsonutils']
    version = 'v0.29.2'
    hash = 'sha256-T1nPqwt/A5KkFAyDHNypzdHYLUTIIt5f7fkzxKeWHgo='

  [mod.'github.com/go-openapi/swag/loading']
    version = 'v0.29.2'
    hash = 'sha256-veNdHbkDEtyvo/aV190IE/cNOdGYLkXEUJapxKKdXVg='

  [mod.'github.com/go-openapi/swag/mangling']
    version = 'v0.29.2'
    hash = 'sha256-Xi6u5NRvwr1aJSAleLFJM9Vab+Oub7Eiw9VMBlfT6aY='

  [mod.'github.com/go-openapi/swag/netutils']
    version = 'v0.29.2'
    hash = 'sha256-cSujSQnZBBzOR4ZhdMAXRvkU9LsvOLE/PiBAguypk+A='

  [mod.'github.com/go-openapi/swag/pools']
    version = 'v0.29.2'
    hash = 'sha256-43OfMR/DxizFSqZxwE2RrMuHwnfeyY7XN9rEI63P414='

  [mod.'github.com/go-openapi/swag/stringutils']
    version = 'v0.29.2'
    hash = 'sha256-fHE7mJOrxDsPuCRo/dgKgQSvypCcrOvN+xiapQKZIvk='

  [mod.'github.com/go-openapi/swag/typeutils']
    version = 'v0.29.2'
    hash = 'sha256-CGLvP7gIgRJzCcXNhw6a/Oa8EnOfaUpEh0So8PEuMJk='

  [mod.'github.com/go-openapi/swag/yamlutils']
    version = 'v0.29.2'
    hash = 'sha256-6AOW/sHZISS/WMhM9HNMGSCe/b7G41y7G+4+OEG1lhY='

  [mod.'github.com/go-task/slim-sprig/v3']
    version = 'v3.0.0'
    hash = 'sha256-vCCw4MXVBm33VNLXcOBccVDD1CSnzDvDdWB6w5FN1cA='

  [mod.'github.com/google/cel-go']
    version = 'v0.31.0'
    hash = 'sha256-/ijimhr93/ZtFBIz0Y8ZJd/6zKpZHp2BmWRMYeHoG6s='

  [mod.'github.com/google/gnostic-models']
    version = 'v0.7.1'
    hash = 'sha256-dfSFaYzgD4HrdL6ZsN8V9w0SMzx0WXl38dIy4dnjhhc='

  [mod.'github.com/google/go-cmp']
    version = 'v0.7.0'
    hash = 'sha256-JbxZFBFGCh/Rj5XZ1vG94V2x7c18L8XKB0N9ZD5F2rM='

  [mod.'github.com/google/pprof']
    version = 'v0.0.0-20260906184651-6331bc6350fe'
    hash = 'sha256-b0aofDeRDJ3wpHNHUsPAbdY052P2PxDhG4wP9zMB8ok='

  [mod.'github.com/google/uuid']
    version = 'v1.6.0'
    hash = 'sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw='

  [mod.'github.com/grpc-ecosystem/grpc-gateway/v2']
    version = 'v2.30.0'
    hash = 'sha256-SKvojuMn48wxg9Dd8D0BcS4PZO3OHIFOJEMYlpvgLsk='

  [mod.'github.com/inconshreveable/mousetrap']
    version = 'v1.1.0'
    hash = 'sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE='

  [mod.'github.com/json-iterator/go']
    version = 'v1.1.12'
    hash = 'sha256-To8A0h+lbfZ/6zM+2PpRpY3+L6725OPC66lffq6fUoM='

  [mod.'github.com/modern-go/concurrent']
    version = 'v0.0.0-20180306012644-bacd9c7ef1dd'
    hash = 'sha256-OTySieAgPWR4oJnlohaFTeK1tRaVp/b0d1rYY8xKMzo='

  [mod.'github.com/modern-go/reflect2']
    version = 'v1.0.3-0.20250322232337-35a7c28c31ee'
    hash = 'sha256-0pkWWZRB3lGFyzmlxxrm0KWVQo9HNXNafaUu3k+rE1g='

  [mod.'github.com/munnerz/goautoneg']
    version = 'v0.0.0-20191010083416-a7dc8b61c822'
    hash = 'sha256-79URDDFenmGc9JZu+5AXHToMrtTREHb3BC84b/gym9Q='

  [mod.'github.com/onsi/ginkgo/v2']
    version = 'v2.33.0'
    hash = 'sha256-dbprIPI9nmIWGqO9p1kG5W5rDpcDMZwvigmd3CmG3Sk='

  [mod.'github.com/onsi/gomega']
    version = 'v1.44.0'
    hash = 'sha256-xSjOiuDOVt9GGtagJPD8UF3Do3ZnkgaQ3CALnONJk6Y='

  [mod.'github.com/pmezard/go-difflib']
    version = 'v1.0.1-0.20181226105442-5d4384ee4fb2'
    hash = 'sha256-XA4Oj1gdmdV/F/+8kMI+DBxKPthZ768hbKsO3d9Gx90='

  [mod.'github.com/prometheus/client_golang']
    version = 'v1.24.1'
    hash = 'sha256-HAOFVYyPiU7hVS1XXMMjkbGgTT7/UN0zVHXYOnjr7is='

  [mod.'github.com/prometheus/client_model']
    version = 'v0.6.3'
    hash = 'sha256-uYXpFkXMT4AXWJShrCRnu51vhGQAuAU3LFQhhGVJ+74='

  [mod.'github.com/prometheus/common']
    version = 'v0.71.0'
    hash = 'sha256-94kki7QNQjmL5UFgJfqN5qeLC/dCqMEevxCHHKyMqUk='

  [mod.'github.com/prometheus/procfs']
    version = 'v0.22.0'
    hash = 'sha256-TRwVHKgW4NnPuC6Me38OD57ccM8AfnS7IxtcAx2TAH4='

  [mod.'github.com/spf13/cobra']
    version = 'v1.10.2'
    hash = 'sha256-nbRCTFiDCC2jKK7AHi79n7urYCMP5yDZnWtNVJrDi+k='

  [mod.'github.com/spf13/pflag']
    version = 'v1.0.10'
    hash = 'sha256-uDPnWjHpSrzXr17KEYEA1yAbizfcsfo5AyztY2tS6ZU='

  [mod.'github.com/x448/float16']
    version = 'v0.8.4'
    hash = 'sha256-VKzMTMS9pIB/cwe17xPftCSK9Mf4Y6EuBEJlB4by5mE='

  [mod.'go.opentelemetry.io/auto/sdk']
    version = 'v1.2.1'
    hash = 'sha256-73bFYhnxNf4SfeQ52ebnwOWywdQbqc9lWawCcSgofvE='

  [mod.'go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp']
    version = 'v0.71.0'
    hash = 'sha256-E5YtRLrs1/LqpvPt6LzC+sDpmxSROgpNmgca5s6iyCg='

  [mod.'go.opentelemetry.io/otel']
    version = 'v1.46.0'
    hash = 'sha256-2+xTacXn22hsJuMGGgXwazMbP/ZW5gkPRnf+rNUZgvQ='

  [mod.'go.opentelemetry.io/otel/exporters/otlp/otlptrace']
    version = 'v1.46.0'
    hash = 'sha256-dhQCMAwny2CrgH3iJfTW0r0klpi7os0nht3zdLeWL6E='

  [mod.'go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc']
    version = 'v1.46.0'
    hash = 'sha256-qIv7G8ADgdnitDv9+jQUYBARM6zUtt9kBX5NCNKbB40='

  [mod.'go.opentelemetry.io/otel/metric']
    version = 'v1.46.0'
    hash = 'sha256-cY1DXXzRfcP0kKh7oBzowbu6kbFr3jANiEVyMlD5Bt8='

  [mod.'go.opentelemetry.io/otel/sdk']
    version = 'v1.46.0'
    hash = 'sha256-bDS4r1NfK2jZmTx5KUcrPJpPC2Men1lOuEKhy3vkMxc='

  [mod.'go.opentelemetry.io/otel/trace']
    version = 'v1.46.0'
    hash = 'sha256-zfj85gCR5Z3v1N+8nlOO+6+FVShaL/7Vb/3lXjdXnnw='

  [mod.'go.opentelemetry.io/proto/otlp']
    version = 'v1.11.0'
    hash = 'sha256-jBcVUiab9mWgLmPsrCYK7sC2j15AJ47QJM4prnqGGkE='

  [mod.'go.uber.org/multierr']
    version = 'v1.11.0'
    hash = 'sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0='

  [mod.'go.uber.org/zap']
    version = 'v1.28.0'
    hash = 'sha256-x+MIioLe/gBKjZyRc8shaBR5nO5Pv++8U9gHPZ5W+5A='

  [mod.'go.yaml.in/yaml/v2']
    version = 'v2.4.4'
    hash = 'sha256-ecT2ZXw7iT+63J4210xA6sMz0fUFXmDzLwZe2FzaNFU='

  [mod.'go.yaml.in/yaml/v3']
    version = 'v3.0.5'
    hash = 'sha256-ygho+GU5kE7vPMx+dZYyNfCaeMjNxj66XmrcVf3afFE='

  [mod.'golang.org/x/exp']
    version = 'v0.0.0-20260908205506-85c1c2202aba'
    hash = 'sha256-g/gNDzulP2hxBtZf3w2cASzcWbUAI6r0Q9zy5Q/wrRQ='

  [mod.'golang.org/x/mod']
    version = 'v0.41.0'
    hash = 'sha256-euzxa6DC2qmU+LgEwjOM71nc/lRrU9XRC9nESAaDw6Q='

  [mod.'golang.org/x/net']
    version = 'v0.59.0'
    hash = 'sha256-EGnbU9mIAvXqx4vEIWJDt+lZgs/YsUngAFJwmFSc5Tc='

  [mod.'golang.org/x/oauth2']
    version = 'v0.37.0'
    hash = 'sha256-CbL8ICe9yooSIiVL8F3UnYY/NayjpI2C7sueOauW2EI='

  [mod.'golang.org/x/sync']
    version = 'v0.23.0'
    hash = 'sha256-nF8YZFVC+TitjkderlqgGwJkuMqJCxI+fIElVLjBT2M='

  [mod.'golang.org/x/sys']
    version = 'v0.48.0'
    hash = 'sha256-u+LwI76YIeg1asQKZItD2mnL4Yvx8veLhBuL8wv60Ls='

  [mod.'golang.org/x/term']
    version = 'v0.46.0'
    hash = 'sha256-w/LexmQ91G8N1zdjIujuaEIONVfAg7U/DciHVYp0+QY='

  [mod.'golang.org/x/text']
    version = 'v0.42.0'
    hash = 'sha256-bviKbNmkN4Yf2dpgwmP6yNcZEakCcv1R+YyAxCdJGkY='

  [mod.'golang.org/x/time']
    version = 'v0.16.0'
    hash = 'sha256-OvekWcaTHMs5n3Img4EmYaORRgSmybBS+tObSnPqftY='

  [mod.'golang.org/x/tools']
    version = 'v0.50.0'
    hash = 'sha256-BjwWAoexahydRI7Tn98NMRfRPlW8ag5jTENGODYFTaU='

  [mod.'gomodules.xyz/jsonpatch/v2']
    version = 'v2.5.0'
    hash = 'sha256-L3Xy24GTtcDHmMgc9rlgUm3GrxFO7XQKJhfYIr3li1s='

  [mod.'google.golang.org/genproto/googleapis/api']
    version = 'v0.0.0-20260921155816-b14227669459'
    hash = 'sha256-vFPDopJXc/dMuPxwrcc2zGxP3UyF8E7PzAs1YmBnlGo='

  [mod.'google.golang.org/genproto/googleapis/rpc']
    version = 'v0.0.0-20260921155816-b14227669459'
    hash = 'sha256-qBJJ3Go2HqyEE+jp6FMafhXbMBbA/PIXvbdROnLPAYA='

  [mod.'google.golang.org/grpc']
    version = 'v1.84.0'
    hash = 'sha256-gUDleBLGxwuzhA0emDRNAr1GnPlMfjgpkOX9u/0WsOk='

  [mod.'google.golang.org/protobuf']
    version = 'v1.36.12'
    hash = 'sha256-MKd0AdkWEe2A79mGPzOY5I76nMqTsGJKQNPJOKyOwkQ='

  [mod.'gopkg.in/evanphx/json-patch.v4']
    version = 'v4.13.0'
    hash = 'sha256-1iyZpBaeBLmNkJ3T4A9fAEXEYB9nk9V02ug4pwl5dy0='

  [mod.'gopkg.in/inf.v0']
    version = 'v0.9.1'
    hash = 'sha256-z84XlyeWLcoYOvWLxPkPFgLkpjyb2Y4pdeGMyySOZQI='

  [mod.'k8s.io/api']
    version = 'v0.37.1'
    hash = 'sha256-T7DJwuBM8gGHWslVG++OZLrz6hNVmgITFZq9eaFeiT4='

  [mod.'k8s.io/apiextensions-apiserver']
    version = 'v0.37.1'
    hash = 'sha256-CSXK3fqUu4QzZ4yLK/+1MqP9/ttwOlB6yGFv28OFxxw='

  [mod.'k8s.io/apimachinery']
    version = 'v0.37.1'
    hash = 'sha256-FTwhtzno2HVYqVCLsmTyoGyA7BSR3igJw5mES4hT7rM='

  [mod.'k8s.io/apiserver']
    version = 'v0.37.1'
    hash = 'sha256-A9anI9p44lH4C7t7kD+8rLYbSZOdufPT9my5NL5Na18='

  [mod.'k8s.io/client-go']
    version = 'v0.37.1'
    hash = 'sha256-6gMR34//xpdjMDAz169Kj2xb4leP/MzqT1BM48n6eq4='

  [mod.'k8s.io/component-base']
    version = 'v0.37.1'
    hash = 'sha256-FwHV3NLqh3g+UtlSZ33HmiHJwtk4haINN7UEKashPa4='

  [mod.'k8s.io/klog/v2']
    version = 'v2.140.0'
    hash = 'sha256-TbA5ZdLRzxa7WRnz3zgPPtTplgC33eY9yKKqVFDrPWU='

  [mod.'k8s.io/kube-openapi']
    version = 'v0.0.0-20260721132016-d427ff9ee9ad'
    hash = 'sha256-/ZpSQoKak2V16wkm3voqS4oow2zCP5vJ4znIQQLKsLY='

  [mod.'k8s.io/streaming']
    version = 'v0.37.1'
    hash = 'sha256-4W7hLvTbWk+BRaWELOO04dRFIFZASmQ8Z412jlJeZcA='

  [mod.'k8s.io/utils']
    version = 'v0.0.0-20260707023825-cf1189d6abe3'
    hash = 'sha256-DBYXOtMHB8jsC8CcjH+iLEkzgYQwAOYtIlTsqQtpHMw='

  [mod.'sigs.k8s.io/apiserver-network-proxy/konnectivity-client']
    version = 'v0.36.0'
    hash = 'sha256-uplhIPtVyh928dP7Jl9FszJP15smUEdKIP3vMyXA8Hg='

  [mod.'sigs.k8s.io/controller-runtime']
    version = 'v0.25.1'
    hash = 'sha256-0yKogqrZbCD0vonR5lhsa8Fy09SBVcgv+5Lf7aefmYA='

  [mod.'sigs.k8s.io/json']
    version = 'v0.0.0-20260909141634-11ed52e25bc5'
    hash = 'sha256-Dj5Vcvq3ETZtUpMO1ALu93zwG5ltne7LjMS7lzBL9KY='

  [mod.'sigs.k8s.io/randfill']
    version = 'v1.0.0'
    hash = 'sha256-xldQxDwW84hmlihdSOFfjXyauhxEWV9KmIDLZMTcYNo='

  [mod.'sigs.k8s.io/structured-merge-diff/v6']
    version = 'v6.4.2'
    hash = 'sha256-Q4GT7pinbkhNOae9Q3WuTKAVOLqNvrP9EfrEDEM1S3I='

  [mod.'sigs.k8s.io/yaml']
    version = 'v1.6.0'
    hash = 'sha256-49hg7IVPzwxeovp+HTMiWa/10NMMTSTjAdCmIv6p9dw='
