---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - pods
  - secrets
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enclave.unmango.dev
  resources:
  - enclaveclaims
  - enclavepools
  - enclaves
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enclave.unmango.dev
  resources:
  - enclaveclaims/finalizers
  - enclavepools/finalizers
  - enclaves/finalizers
  verbs:
  - update
- apiGroups:
  - enclave.unmango.dev
  resources:
  - enclaveclaims/status
  - enclavepools/status
  - enclaves/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - roles
  verbs:
  - bind
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
